### ISSUE TITLE
initialisation

### ISSUE THREAD

**Issue by Bonnarel** [ivoa/TimeSeriesDiscoveryAndAccess#2]
You have to create a README.md

**Comment by molinaro-m** [comment]
hi @Bonnarel : would you like me to set up the initialisation, so you can work from there?

**Comment by Bonnarel** [comment]
Sure, Thanks
Le 03/06/2021 à 10:58, Marco Molinaro a écrit :

**Comment by jd-au** [comment]
I've created a very basic readme file. You should be right to fork the repository now Francois

**Comment by molinaro-m** [comment]
thanks @jd-au for picking this up :)

**Comment by Bonnarel** [comment]
thanks james and Marco, i was able to fork
Cheers
François
Le 03/06/2021 à 11:12, Marco Molinaro a écrit :

**Comment by molinaro-m** [comment]
closed via #3
